/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AsyncDummy: typeof import('./components/AsyncDummy.vue')['default']
    BaseAvatar: typeof import('./components/base/BaseAvatar.vue')['default']
    BaseCheckbox: typeof import('./components/base/BaseCheckbox.vue')['default']
    ErrorMessage: typeof import('./components/shared/ErrorMessage.vue')['default']
    BaseImg: typeof import('./components/base/BaseImg.vue')['default']
    BaseInput: typeof import('./components/base/BaseInput.vue')['default']
    BaseSeparatorPoint: typeof import('./components/base/BaseSeparatorPoint.vue')['default']
    BaseSwitch: typeof import('./components/base/BaseSwitch.vue')['default']
    BaseSwitchTheme: typeof import('./components/base/BaseSwitchTheme.vue')['default']
    CardJob: typeof import('./components/cards/CardJob.vue')['default']
    CardJobContent: typeof import('./components/cards/CardJobContent.vue')['default']
    CardJobImg: typeof import('./components/cards/CardJobImg.vue')['default']
    CardJobSummary: typeof import('./components/cards/CardJobSummary.vue')['default']
    Components: typeof import('./components/index.vue')['default']
    DummyComponent: typeof import('./components/DummyComponent.vue')['default']
    FormFilter: typeof import('./components/forms/FormFilter.vue')['default']
    FormFIlter: typeof import('./components/forms/FormFIlter.vue')['default']
    GalleryJobs: typeof import('./components/cards/GalleryJobs.vue')['default']
    GallerySkeleton: typeof import('./components/cards/GallerySkeleton.vue')['default']
    IndexDummy: typeof import('./components/indexDummy.vue')['default']
    JobsContainer: typeof import('./components/sections/JobsContainer.vue')['default']
    LayoutHeader: typeof import('./components/layouts/LayoutHeader.vue')['default']
    LayoutJobDetailFooter: typeof import('./components/layouts/LayoutJobDetailFooter.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
