export { JobListSchema } from './JobList.response'
export { JobDataSchema } from './JobData.response'
export type { JobListResponse } from './JobList.response'
export type { JobDataResponse } from './JobData.response'
export type { JobData, JobType } from './JobData'
export type { Color, HexadecimalColor } from './Color'
// export type { Pokemon } from './pokemon'
